CREATE DATABASE IF NOT EXISTS animefigurestore;

USE animefigurestore;

CREATE TABLE `categories` (
                              `category_id` int NOT NULL AUTO_INCREMENT,
                              `category_name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
                              `is_deleted` tinyint(1) DEFAULT '0',
                              `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                              PRIMARY KEY (`category_id`)
);

CREATE TABLE `orders` (
                          `order_id` int NOT NULL AUTO_INCREMENT,
                          `user_id` int DEFAULT NULL,
                          `total` decimal(10,0) DEFAULT NULL,
                          `delivery_address` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
                          `payment_option` int DEFAULT NULL COMMENT '0: pay offline, 1: pay online',
                          `payment_status` int DEFAULT NULL COMMENT '0: pending, 1: success, 2: failed',
                          `vnpay_transaction_id` int DEFAULT NULL COMMENT 'vnp_TxnRef: ma giao dich ben vnpay',
                          `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                          PRIMARY KEY (`order_id`)
);

CREATE TABLE `orders_detail` (
                                 `order_id` int NOT NULL,
                                 `product_id` int NOT NULL,
                                 `unit_price` decimal(10,0) DEFAULT NULL COMMENT 'gia luc tinh tien',
                                 `amount` decimal(10,0) DEFAULT NULL,
                                 `sub_total` decimal(10,0) DEFAULT NULL,
                                 PRIMARY KEY (`order_id`,`product_id`)
);

CREATE TABLE `products` (
                            `product_id` int NOT NULL AUTO_INCREMENT,
                            `product_name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
                            `product_price` decimal(10,0) NOT NULL,
                            `product_images` text COMMENT 'danh sach anh',
                            `product_quantity` int DEFAULT NULL,
                            `product_description` text,
                            `discount` text COMMENT 'gia tri giam gia 50%, 50000',
                            `category_id` int NOT NULL,
                            `is_deleted` tinyint(1) DEFAULT '0',
                            `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                            `url_image` text,
                            PRIMARY KEY (`product_id`)
);

CREATE TABLE `roles` (
                         `role_id` int NOT NULL AUTO_INCREMENT,
                         `role_name` varchar(50) NOT NULL,
                         `roles_descripion` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
                         `is_deleted` tinyint(1) DEFAULT NULL,
                         `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                         PRIMARY KEY (`role_id`)
);

CREATE TABLE `users` (
                         `user_id` int NOT NULL AUTO_INCREMENT,
                         `username` varchar(50) NOT NULL,
                         `password` varchar(255) NOT NULL,
                         `fullname` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
                         `address` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
                         `phonenumber` varchar(12) DEFAULT NULL,
                         `email` varchar(255) DEFAULT NULL,
                         `dob` varchar(10) DEFAULT NULL,
                         `avatar` text,
                         `is_deleted` tinyint(1) DEFAULT NULL,
                         `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                         `token` varchar(255) DEFAULT NULL,
                         `provider` varchar(15) DEFAULT NULL,
                         `is_Logged` tinyint(1) DEFAULT NULL,
                         `url_image` text,
                         `oauth2_id` text,
                         PRIMARY KEY (`user_id`)
);

CREATE TABLE `users_roles` (
                               `user_id` int NOT NULL,
                               `role_id` int NOT NULL,
                               PRIMARY KEY (`user_id`,`role_id`)
);

INSERT INTO `roles` (`role_name`,`roles_descripion`, `is_deleted`,`created_date`)
VALUES ('admin','manage everything',0,null),
       ('salesperson','manage product price, customer, shipping, order and sales report',0,null),
       ('editor','manage categories, brands, product, artical, and menus',0,null),
       ('shipper','view product, view order, update order status',0,null),
       ('assistant','manage question and views',0,null),
       ('client','only order product and update user',0,null);

INSERT INTO `users` (`username`,`password`, `fullname`,`address`, `phonenumber`, `email`, `dob`, `avatar`, `is_deleted`, `created_date`, `token`, `provider`, `is_Logged`, `url_image`, `oauth2_id`)
VALUES ('9Z2RTU0','$2a$10$EJk68SXctvdpZph7xLNXmeMqfwGDBmz.G9pQG9O/fQKrCaZDVpwlm','acs 123','Thế giới hoàn mỹ','0981219991','9Z2RTU0@yopmail.com','01/01/1998','999.jpg',0,NULL,'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5WjJSVFUwIn0.QzY_iZ6Lc_h7pbbXKKfi3vcx_8TqAPEQuMksZzjL7wc',NULL,0,NULL,NULL),
       ('JXRN231','$2a$10$45ND50iWccoLi1QWsMQNb.QKTCUqCSQWZ4WoMRwTc7WaEBENb52py','JXRN231','Nha trang, khánh hòa','0983172229','JXRN231@yopmail.com','23/03/1990','',0,NULL,'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKWFJOMjMxIn0.pkevRKnItrYYKz5vLVTRY4bjc-BFH7AlgsR8SgoNxFc',NULL,0,NULL,NULL),
       ('2BUEQXBM2','$2a$10$8iuEP/WTmM7VidAumDN9EuHT0IO16O8pJY8Wklefc9/jEZEfj1cyy','2BUEQXBM2','Nha trang, khánh hòa','0983172229','2BUEQXBM2@yopmail.com','23/03/1990','',1,NULL,'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyQlVFUVhCTTIifQ.Ub_yQ4_KNgO9zlFtL5EvfuUdSpgBhVOUG4kBz-4CvjM',NULL,0,NULL,NULL),
       ('9QEFJQ93','$2a$10$oZP8HZOFQs2vpmLK/rEa2ecUUWwdwWkjcA67wF4J4BpEcBwgcusJO','9QEFJQ93','Nha trang, khánh hòa','0983172229','9QEFJQ93@yopmail.com','23/03/1990','',1,NULL,'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5UUVGSlE5MyJ9.S_gl2pTmT0HafWIfCbAK8f7STGyKHxngofm0GNp2wNA',NULL,0,NULL,NULL),
       ('TVLMC4','$2a$10$3e1p5Ip6IrT3PiTyFX116eUUiSTTy2/aEUp939B2IANfgulmKZ4Jy','TVLMC4','Nha trang, khánh hòa','0983172229','TVLMC4@yopmail.com','23/03/1990','',1,NULL,'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUVkxNQzQifQ.yGqmYJlVOHkYFHG73DbPuSOGQTSav_oJ92KyTddwqcA',NULL,0,NULL,NULL),
       ('8SH2FW5','$2a$10$oLOFsiOky2658mxShmN1keZiv1R8uoxVKkE5Ti9rmKDbCcG.WuexC','8SH2FW5','Nha trang, khánh hòa','0983172229','8SH2FW5@yopmail.com','23/03/1990','',1,NULL,'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4U0gyRlc1In0.7yo1Zw7WoFE2BmcihQ4LpdI4IG5FPNSDyJwajjNVVxk',NULL,0,NULL,NULL),
       ('8C15L6E26','$2a$10$g0X42KNisA6925l4PssjgexgtIiaYzW2iLULOb2bGsC6.hH9fV2J2','8C15L6E26','Nha trang, khánh hòa','0983172229','8C15L6E26@yopmail.com','23/03/1990','',1,NULL,'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4QzE1TDZFMjYifQ.TcHXwO_BaVZSZWNh06ei2lzVwlgCkJPCpYpn5pYTMPM',NULL,0,NULL,NULL),
       ('N7O5MJ47','$2a$10$c5m23FyjZ8MVU2vx0H1YNe9IY2ZwyXh/rsr5rDXzS4KNzs52itSS6','N7O5MJ47','Nha trang, khánh hòa','0983172229','N7O5MJ47@yopmail.com','23/03/1990','',1,NULL,'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJON081TUo0NyJ9.zjenlFe09XXIMZv3Bo4xta1VdsnxV_aQKUph3kP88Iw',NULL,0,NULL,NULL),
       ('9XA3TKAV8','$2a$10$RR2VrSPGUVgx4w6njZo/e.x2GA2dMdIO21AXIvqRIisBRhDwpVZpK','9XA3TKAV8','Nha trang, khánh hòa','0983172229','9XA3TKAV8@yopmail.com','23/03/1990','',1,NULL,'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5WEEzVEtBVjgifQ.FUBgrmHi3D37dnvdyJYMXmGBvISF8VuR5CkAdkRWDXw',NULL,0,NULL,NULL),
       ('FHBK409','$2a$10$qMEbUZ4SaDQsmoEHKaK76.moWBGe6/l5sj84/x39ylhzLoocwktK2','FHBK409','Nha trang, khánh hòa','0983172229','FHBK409@yopmail.com','23/03/1990','',1,NULL,'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJGSEJLNDA5In0.McIzEPCT_wDcs_GGRufHhZQLxoWkjzv10vEWs78WHSg',NULL,0,NULL,NULL);

INSERT INTO `users_roles` (`user_id`, `role_id`)
VALUES (1,1),
       (1,5),
       (2,1),
       (3,2),
       (4,3),
       (5,4),
       (6,5),
       (7,6),
       (8,4),
       (9,6),
       (10,6);

INSERT INTO `categories` (`category_name`, `is_deleted`, `created_date`)
VALUES ('Honkai Impact 3',0,null),
       ('Honkai Star Rail',0,null),
       ('Zenless Zeno Zero',0,null),
       ('Genshin Impact',0,null),
       ('Manga / Anime / Game khác',0,null),
       ('Sản phẩm mới',0,null),
       ('Honkai & Genshin khác',0,null),
       ('test cate 123',0,null);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES ('Khối Acrylic cát chảy chủ đề Flower Festival - Honkai Impact 3',205000,'1.webp',1220,'Mô tả chi tiết: Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Standee chủ đề Flower Festival - Honkai Impact 3',205000,'2.jpg',1111,'Mô tả chi tiết: Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Huy hiệu tròn chủ đề Flower Festival - Honkai Impact 3',70000,'3.webp',1121,'Mô tả chi tiết: Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Vé Laser chủ đề Flower Festival - Honkai Impact 3',50000,'4.webp',1121,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Elysia - Honkai Impact 3 - Fenghua Studio',6600000,'5.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Elysia: Wedding ver - Honkai Impact 3 - Yuannai Studio',5000000,'6.jpeg',545,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Búp bê bông Lunar Vow - Honkai Impact 3 - Mantou',620000,'7.jpeg',887,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Búp bê bông Elysia Herrscher of Human: Hương Đào Mùa Xuân - Honkai Impact 3 - Ajong',670000,'8.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Búp bê bông Elf Elysia - Honkai Impact 3 - Ajong',670000,'9.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Card bo góc Honkai Impact 3 - Caida Creation Limited Company x miHoYo',630000,'10.webp',1811,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Giá đỡ kính Acrylic chủ đề Nhân vật Raiden Mei - Honkai Impact 3',210000,'11.webp',1918,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Túi đeo Lunar Vow chủ đề \"Lời Hứa Dưới Ánh Trăng\" - Honkai Impact 3',1030000,'12.webp',2000,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Blindbox Huy hiệu tròn dòng CG Honkai Impact 3',70000,'13.webp',1912,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Giấy màu PET dòng CG Honkai Impact 3',150000,'14.webp',989,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Vé Laser chủ đề Flower Festival - Honkai Impact 3',50000,'4.webp',1121,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Elysia - Honkai Impact 3 - Fenghua Studio',6600000,'5.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Elysia: Wedding ver - Honkai Impact 3 - Yuannai Studio',5000000,'6.jpeg',545,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Búp bê bông Lunar Vow - Honkai Impact 3 - Mantou',620000,'7.jpeg',887,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Búp bê bông Elysia Herrscher of Human: Hương Đào Mùa Xuân - Honkai Impact 3 - Ajong',670000,'8.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Búp bê bông Elf Elysia - Honkai Impact 3 - Ajong',670000,'9.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Card bo góc Honkai Impact 3 - Caida Creation Limited Company x miHoYo',630000,'10.webp',1811,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Giá đỡ kính Acrylic chủ đề Nhân vật Raiden Mei - Honkai Impact 3',210000,'11.webp',1918,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Túi đeo Lunar Vow chủ đề \"Lời Hứa Dưới Ánh Trăng\" - Honkai Impact 3',1030000,'12.webp',2000,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
       ('Blindbox Huy hiệu tròn dòng CG Honkai Impact 3',70000,'13.webp',1912,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES
    ('Giấy màu PET dòng CG Honkai Impact 3',150000,'14.webp',989,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser chủ đề Flower Festival - Honkai Impact 3',50000,'4.webp',1121,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia - Honkai Impact 3 - Fenghua Studio',6600000,'5.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia: Wedding ver - Honkai Impact 3 - Yuannai Studio',5000000,'6.jpeg',545,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Lunar Vow - Honkai Impact 3 - Mantou',620000,'7.jpeg',887,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Elysia Herrscher of Human: Hương Đào Mùa Xuân - Honkai Impact 3 - Ajong',670000,'8.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Elf Elysia - Honkai Impact 3 - Ajong',670000,'9.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Card bo góc Honkai Impact 3 - Caida Creation Limited Company x miHoYo',630000,'10.webp',1811,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Giá đỡ kính Acrylic chủ đề Nhân vật Raiden Mei - Honkai Impact 3',210000,'11.webp',1918,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Túi đeo Lunar Vow chủ đề \"Lời Hứa Dưới Ánh Trăng\" - Honkai Impact 3',1030000,'12.webp',2000,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Blindbox Huy hiệu tròn dòng CG Honkai Impact 3',70000,'13.webp',1912,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Giấy màu PET dòng CG Honkai Impact 3',150000,'14.webp',989,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia - Honkai Impact 3 - Fenghua Studio',6600000,'5.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia: Wedding ver - Honkai Impact 3 - Yuannai Studio',5000000,'6.jpeg',545,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Lunar Vow - Honkai Impact 3 - Mantou',620000,'7.jpeg',887,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Elysia Herrscher of Human: Hương Đào Mùa Xuân - Honkai Impact 3 - Ajong',670000,'8.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Elf Elysia - Honkai Impact 3 - Ajong',670000,'9.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Card bo góc Honkai Impact 3 - Caida Creation Limited Company x miHoYo',630000,'10.webp',1811,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Giá đỡ kính Acrylic chủ đề Nhân vật Raiden Mei - Honkai Impact 3',210000,'11.webp',1918,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Túi đeo Lunar Vow chủ đề \"Lời Hứa Dưới Ánh Trăng\" - Honkai Impact 3',1030000,'12.webp',2000,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Blindbox Huy hiệu tròn dòng CG Honkai Impact 3',70000,'13.webp',1912,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Giấy màu PET dòng CG Honkai Impact 3',150000,'14.webp',989,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser chủ đề Flower Festival - Honkai Impact 3',50000,'4.webp',1121,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia - Honkai Impact 3 - Fenghua Studio',6600000,'5.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Elysia: Wedding ver - Honkai Impact 3 - Yuannai Studio',5000000,'6.jpeg',545,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Lunar Vow - Honkai Impact 3 - Mantou',620000,'7.jpeg',887,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Elysia Herrscher of Human: Hương Đào Mùa Xuân - Honkai Impact 3 - Ajong',670000,'8.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Elf Elysia - Honkai Impact 3 - Ajong',670000,'9.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Card bo góc Honkai Impact 3 - Caida Creation Limited Company x miHoYo',630000,'10.webp',1811,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Giá đỡ kính Acrylic chủ đề Nhân vật Raiden Mei - Honkai Impact 3',210000,'11.webp',1918,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Túi đeo Lunar Vow chủ đề \"Lời Hứa Dưới Ánh Trăng\" - Honkai Impact 3',1030000,'12.webp',2000,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Blindbox Huy hiệu tròn dòng CG Honkai Impact 3',70000,'13.webp',1912,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Giấy màu PET dòng CG Honkai Impact 3',150000,'14.webp',989,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn Honkai MEME - Honkai Impact 3',70000,'15.webp',9891,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Móc khóa chibi dòng Honkai Impact 3 Vol.2',120000,'16.webp',1181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Thẻ sưu tập chibi Laser dòng Honkai Impact 3 Vol.2',55000,'17.webp',1712,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Standee Vết Thánh ver 2.0 - Honkai Impact 3',205000,'18.webp',9191,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bộ huy hiệu Vết Thánh ver 2.0 - Honkai Impact 3',110000,'19.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES
    ('Huy hiệu tròn 13 Anh Kiệt Trục Hỏa - Honkai Impact 3',75000,'20.webp',181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Seele Vollerei: Herrscher of Rebirth - Honkai Impact 3 - Mantou',620000,'21.webp',192,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Bronya Zaychik: SilverWing \"Thái Độ Phi Phàm\" - Honkai Impact 3 - Mantou',620000,'22.webp',181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bưu thiếp Xổ số trúng thưởng 100% - Honkai Impact 3',220000,'23.webp',191,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa chủ đề \"Lucky Life\" - Honkai Impact 3',165000,'24.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu chủ đề \"Lucky Life\" - Honkai Impact 3',70000,'25.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Huy hiệu tròn nhân vật 2.0 - Honkai Impact 3',70000,'26.webp',1987,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa nhân vật 2.0 - Honkai Impact 3',140000,'27.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee nhân vật 2.0 - Honkai Impact 3',205000,'28.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bộ Sticker emoji Honkai MEME - Honkai Impact 3',60000,'29.webp',555,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser chủ đề \"Lucky Life\" - Honkai Impact 3',60000,'30.webp',1871,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser nhân vật 2.0 - Honkai Impact 3',50000,'31.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Đồ chơi Yoyo của Senadina - Honkai Impact 3  - miHoYo x Auldey',180000,'32.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Seele Vollerei: Herrscher of Rebirth \"Trong Đêm Đen Vĩnh Hằng\" - Honkai Impact 3 - Arctic Wolf Studio',7500000,'33.jpeg',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Elysia Herrscher of Human:Ego - Honkai Impact 3 - Mantou',620000,'34.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Hộp trưng bày Mô hình Fu hua: Cerulean Court - Honkai Impact 3 x APEX Toys - Aowobox',1000000,'35.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Card raster CG - Honkai Impact 3',60000,'36.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Bronya Zaychik - Honkai Impact 3 - Lou Lan Studio',6500000,'37.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Mô hình chibi Elysia Giáo Phái \"Ái Môn\" - Honkai Impact 3 - Unoff',405000,'38.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp trưng bày Mô hình chibi Elysia Herrscher of Human EGO - Honkai Impact 3 - Unoff',360000,'39.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc bông Gà Tinh Vệ Điểu - Honkai Impact 3',165000,'40.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà sinh nhật Durandal 2024 - Honkai Impact 3',360000,'41.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa Acrylic cát lún \" Chúc một năm may mắn \" Tết 2024 - Honkai Impact 3',160000,'42.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà Tết 2024 \" Chúc một năm may mắn \" - Honkai Impact 3',1280000,'43.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Hộp quà sinh nhật Fu Hua Garuda 2024 - Honkai Impact 3',360000,'44.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Standee Seele Vollerei: Herrscher of Rebirth - Honkai Impact 3 - Cat House',235000,'45.jpeg',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser chủ đề Flower Festival - Honkai Impact 3',50000,'4.webp',1121,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia - Honkai Impact 3 - Fenghua Studio',6600000,'5.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia: Wedding ver - Honkai Impact 3 - Yuannai Studio',5000000,'6.jpeg',545,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Lunar Vow - Honkai Impact 3 - Mantou',620000,'7.jpeg',887,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Elysia Herrscher of Human: Hương Đào Mùa Xuân - Honkai Impact 3 - Ajong',670000,'8.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Elf Elysia - Honkai Impact 3 - Ajong',670000,'9.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Card bo góc Honkai Impact 3 - Caida Creation Limited Company x miHoYo',630000,'10.webp',1811,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Giá đỡ kính Acrylic chủ đề Nhân vật Raiden Mei - Honkai Impact 3',210000,'11.webp',1918,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Túi đeo Lunar Vow chủ đề \"Lời Hứa Dưới Ánh Trăng\" - Honkai Impact 3',1030000,'12.webp',2000,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Blindbox Huy hiệu tròn dòng CG Honkai Impact 3',70000,'13.webp',1912,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES
    ('Giấy màu PET dòng CG Honkai Impact 3',150000,'14.webp',989,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn Honkai MEME - Honkai Impact 3',70000,'15.webp',9891,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa chibi dòng Honkai Impact 3 Vol.2',120000,'16.webp',1181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Thẻ sưu tập chibi Laser dòng Honkai Impact 3 Vol.2',55000,'17.webp',1712,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee Vết Thánh ver 2.0 - Honkai Impact 3',205000,'18.webp',9191,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bộ huy hiệu Vết Thánh ver 2.0 - Honkai Impact 3',110000,'19.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn 13 Anh Kiệt Trục Hỏa - Honkai Impact 3',75000,'20.webp',181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Seele Vollerei: Herrscher of Rebirth - Honkai Impact 3 - Mantou',620000,'21.webp',192,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Bronya Zaychik: SilverWing \"Thái Độ Phi Phàm\" - Honkai Impact 3 - Mantou',620000,'22.webp',181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bưu thiếp Xổ số trúng thưởng 100% - Honkai Impact 3',220000,'23.webp',191,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa chủ đề \"Lucky Life\" - Honkai Impact 3',165000,'24.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu chủ đề \"Lucky Life\" - Honkai Impact 3',70000,'25.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn nhân vật 2.0 - Honkai Impact 3',70000,'26.webp',1987,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa nhân vật 2.0 - Honkai Impact 3',140000,'27.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee nhân vật 2.0 - Honkai Impact 3',205000,'28.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bộ Sticker emoji Honkai MEME - Honkai Impact 3',60000,'29.webp',555,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser chủ đề \"Lucky Life\" - Honkai Impact 3',60000,'30.webp',1871,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser nhân vật 2.0 - Honkai Impact 3',50000,'31.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Đồ chơi Yoyo của Senadina - Honkai Impact 3  - miHoYo x Auldey',180000,'32.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Seele Vollerei: Herrscher of Rebirth \"Trong Đêm Đen Vĩnh Hằng\" - Honkai Impact 3 - Arctic Wolf Studio',7500000,'33.jpeg',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Elysia Herrscher of Human:Ego - Honkai Impact 3 - Mantou',620000,'34.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp trưng bày Mô hình Fu hua: Cerulean Court - Honkai Impact 3 x APEX Toys - Aowobox',1000000,'35.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Card raster CG - Honkai Impact 3',60000,'36.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bronya Zaychik - Honkai Impact 3 - Lou Lan Studio',6500000,'37.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Mô hình chibi Elysia Giáo Phái \"Ái Môn\" - Honkai Impact 3 - Unoff',405000,'38.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES
    ('Hộp trưng bày Mô hình chibi Elysia Herrscher of Human EGO - Honkai Impact 3 - Unoff',360000,'39.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc bông Gà Tinh Vệ Điểu - Honkai Impact 3',165000,'40.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà sinh nhật Durandal 2024 - Honkai Impact 3',360000,'41.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa Acrylic cát lún \" Chúc một năm may mắn \" Tết 2024 - Honkai Impact 3',160000,'42.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà Tết 2024 \" Chúc một năm may mắn \" - Honkai Impact 3',1280000,'43.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà sinh nhật Fu Hua Garuda 2024 - Honkai Impact 3',360000,'44.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee Seele Vollerei: Herrscher of Rebirth - Honkai Impact 3 - Cat House',235000,'45.jpeg',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser chủ đề Flower Festival - Honkai Impact 3',50000,'4.webp',1121,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia - Honkai Impact 3 - Fenghua Studio',6600000,'5.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia: Wedding ver - Honkai Impact 3 - Yuannai Studio',5000000,'6.jpeg',545,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Lunar Vow - Honkai Impact 3 - Mantou',620000,'7.jpeg',887,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Elysia Herrscher of Human: Hương Đào Mùa Xuân - Honkai Impact 3 - Ajong',670000,'8.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Elf Elysia - Honkai Impact 3 - Ajong',670000,'9.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Card bo góc Honkai Impact 3 - Caida Creation Limited Company x miHoYo',630000,'10.webp',1811,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Giá đỡ kính Acrylic chủ đề Nhân vật Raiden Mei - Honkai Impact 3',210000,'11.webp',1918,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Túi đeo Lunar Vow chủ đề \"Lời Hứa Dưới Ánh Trăng\" - Honkai Impact 3',1030000,'12.webp',2000,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Blindbox Huy hiệu tròn dòng CG Honkai Impact 3',70000,'13.webp',1912,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Giấy màu PET dòng CG Honkai Impact 3',150000,'14.webp',989,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn Honkai MEME - Honkai Impact 3',70000,'15.webp',9891,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa chibi dòng Honkai Impact 3 Vol.2',120000,'16.webp',1181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Thẻ sưu tập chibi Laser dòng Honkai Impact 3 Vol.2',55000,'17.webp',1712,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee Vết Thánh ver 2.0 - Honkai Impact 3',205000,'18.webp',9191,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bộ huy hiệu Vết Thánh ver 2.0 - Honkai Impact 3',110000,'19.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn 13 Anh Kiệt Trục Hỏa - Honkai Impact 3',75000,'20.webp',181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Seele Vollerei: Herrscher of Rebirth - Honkai Impact 3 - Mantou',620000,'21.webp',192,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Bronya Zaychik: SilverWing \"Thái Độ Phi Phàm\" - Honkai Impact 3 - Mantou',620000,'22.webp',181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bưu thiếp Xổ số trúng thưởng 100% - Honkai Impact 3',220000,'23.webp',191,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa chủ đề \"Lucky Life\" - Honkai Impact 3',165000,'24.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu chủ đề \"Lucky Life\" - Honkai Impact 3',70000,'25.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn nhân vật 2.0 - Honkai Impact 3',70000,'26.webp',1987,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa nhân vật 2.0 - Honkai Impact 3',140000,'27.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES
    ('Standee nhân vật 2.0 - Honkai Impact 3',205000,'28.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bộ Sticker emoji Honkai MEME - Honkai Impact 3',60000,'29.webp',555,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser chủ đề \"Lucky Life\" - Honkai Impact 3',60000,'30.webp',1871,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser nhân vật 2.0 - Honkai Impact 3',50000,'31.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Đồ chơi Yoyo của Senadina - Honkai Impact 3  - miHoYo x Auldey',180000,'32.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Seele Vollerei: Herrscher of Rebirth \"Trong Đêm Đen Vĩnh Hằng\" - Honkai Impact 3 - Arctic Wolf Studio',7500000,'33.jpeg',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Elysia Herrscher of Human:Ego - Honkai Impact 3 - Mantou',620000,'34.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp trưng bày Mô hình Fu hua: Cerulean Court - Honkai Impact 3 x APEX Toys - Aowobox',1000000,'35.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Card raster CG - Honkai Impact 3',60000,'36.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bronya Zaychik - Honkai Impact 3 - Lou Lan Studio',6500000,'37.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Mô hình chibi Elysia Giáo Phái \"Ái Môn\" - Honkai Impact 3 - Unoff',405000,'38.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp trưng bày Mô hình chibi Elysia Herrscher of Human EGO - Honkai Impact 3 - Unoff',360000,'39.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc bông Gà Tinh Vệ Điểu - Honkai Impact 3',165000,'40.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà sinh nhật Durandal 2024 - Honkai Impact 3',360000,'41.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa Acrylic cát lún \" Chúc một năm may mắn \" Tết 2024 - Honkai Impact 3',160000,'42.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà Tết 2024 \" Chúc một năm may mắn \" - Honkai Impact 3',1280000,'43.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà sinh nhật Fu Hua Garuda 2024 - Honkai Impact 3',360000,'44.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee Seele Vollerei: Herrscher of Rebirth - Honkai Impact 3 - Cat House',235000,'45.jpeg',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà sinh nhật Kiana Kaslana 2023 - Honkai Impact 3',360000,'46.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee Valkyrie - Honkai Impact 3',205000,'47.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn Valkyrie - Honkai Impact 3',70000,'48.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Gối chữ nhật Không Thức Thời - Đập Nát Tất Cả - Honkai Impact 3',380000,'49.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Lunar Vow: Crimson Love - Honkai Impact 3rd - Arctic Wolf Studio',5600000,'50.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Seele Vollerei & Veliona: \"Mặc Nhiễm Kính Hoa\" - Honkai Impact 3rd - Arctic Wolf Studio',6000000,'51.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà sinh nhật Susannah 2023 - Honkai Impact 3',360000,'52.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp lưu trữ đồ Ngô Pháp Vũ Thiên - Honkai Impact 3',425000,'53.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Gạch Plush Không Thức Thời - Đập Nát Tất Cả - Honkai Impact 3',210000,'54.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser chủ đề Flower Festival - Honkai Impact 3',50000,'4.webp',1121,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia - Honkai Impact 3 - Fenghua Studio',6600000,'5.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia: Wedding ver - Honkai Impact 3 - Yuannai Studio',5000000,'6.jpeg',545,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Lunar Vow - Honkai Impact 3 - Mantou',620000,'7.jpeg',887,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Elysia Herrscher of Human: Hương Đào Mùa Xuân - Honkai Impact 3 - Ajong',670000,'8.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê bông Elf Elysia - Honkai Impact 3 - Ajong',670000,'9.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Card bo góc Honkai Impact 3 - Caida Creation Limited Company x miHoYo',630000,'10.webp',1811,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Giá đỡ kính Acrylic chủ đề Nhân vật Raiden Mei - Honkai Impact 3',210000,'11.webp',1918,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Túi đeo Lunar Vow chủ đề \"Lời Hứa Dưới Ánh Trăng\" - Honkai Impact 3',1030000,'12.webp',2000,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES
    ('Blindbox Huy hiệu tròn dòng CG Honkai Impact 3',70000,'13.webp',1912,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Giấy màu PET dòng CG Honkai Impact 3',150000,'14.webp',989,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn Honkai MEME - Honkai Impact 3',70000,'15.webp',9891,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa chibi dòng Honkai Impact 3 Vol.2',120000,'16.webp',1181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Thẻ sưu tập chibi Laser dòng Honkai Impact 3 Vol.2',55000,'17.webp',1712,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee Vết Thánh ver 2.0 - Honkai Impact 3',205000,'18.webp',9191,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bộ huy hiệu Vết Thánh ver 2.0 - Honkai Impact 3',110000,'19.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn 13 Anh Kiệt Trục Hỏa - Honkai Impact 3',75000,'20.webp',181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Seele Vollerei: Herrscher of Rebirth - Honkai Impact 3 - Mantou',620000,'21.webp',192,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Bronya Zaychik: SilverWing \"Thái Độ Phi Phàm\" - Honkai Impact 3 - Mantou',620000,'22.webp',181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bưu thiếp Xổ số trúng thưởng 100% - Honkai Impact 3',220000,'23.webp',191,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa chủ đề \"Lucky Life\" - Honkai Impact 3',165000,'24.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu chủ đề \"Lucky Life\" - Honkai Impact 3',70000,'25.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn nhân vật 2.0 - Honkai Impact 3',70000,'26.webp',1987,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa nhân vật 2.0 - Honkai Impact 3',140000,'27.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee nhân vật 2.0 - Honkai Impact 3',205000,'28.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bộ Sticker emoji Honkai MEME - Honkai Impact 3',60000,'29.webp',555,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser chủ đề \"Lucky Life\" - Honkai Impact 3',60000,'30.webp',1871,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Vé Laser nhân vật 2.0 - Honkai Impact 3',50000,'31.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Đồ chơi Yoyo của Senadina - Honkai Impact 3  - miHoYo x Auldey',180000,'32.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Seele Vollerei: Herrscher of Rebirth \"Trong Đêm Đen Vĩnh Hằng\" - Honkai Impact 3 - Arctic Wolf Studio',7500000,'33.jpeg',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Búp bê Elysia Herrscher of Human:Ego - Honkai Impact 3 - Mantou',620000,'34.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp trưng bày Mô hình Fu hua: Cerulean Court - Honkai Impact 3 x APEX Toys - Aowobox',1000000,'35.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Card raster CG - Honkai Impact 3',60000,'36.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bronya Zaychik - Honkai Impact 3 - Lou Lan Studio',6500000,'37.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Mô hình chibi Elysia Giáo Phái \"Ái Môn\" - Honkai Impact 3 - Unoff',405000,'38.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp trưng bày Mô hình chibi Elysia Herrscher of Human EGO - Honkai Impact 3 - Unoff',360000,'39.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc bông Gà Tinh Vệ Điểu - Honkai Impact 3',165000,'40.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà sinh nhật Durandal 2024 - Honkai Impact 3',360000,'41.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Móc khóa Acrylic cát lún \" Chúc một năm may mắn \" Tết 2024 - Honkai Impact 3',160000,'42.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà Tết 2024 \" Chúc một năm may mắn \" - Honkai Impact 3',1280000,'43.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà sinh nhật Fu Hua Garuda 2024 - Honkai Impact 3',360000,'44.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee Seele Vollerei: Herrscher of Rebirth - Honkai Impact 3 - Cat House',235000,'45.jpeg',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà sinh nhật Kiana Kaslana 2023 - Honkai Impact 3',360000,'46.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee Valkyrie - Honkai Impact 3',205000,'47.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Huy hiệu tròn Valkyrie - Honkai Impact 3',70000,'48.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Gối chữ nhật Không Thức Thời - Đập Nát Tất Cả - Honkai Impact 3',380000,'49.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Lunar Vow: Crimson Love - Honkai Impact 3rd - Arctic Wolf Studio',5600000,'50.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Seele Vollerei & Veliona: \"Mặc Nhiễm Kính Hoa\" - Honkai Impact 3rd - Arctic Wolf Studio',6000000,'51.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES
    ('Hộp quà sinh nhật Susannah 2023 - Honkai Impact 3',360000,'52.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp lưu trữ đồ Ngô Pháp Vũ Thiên - Honkai Impact 3',425000,'53.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Gạch Plush Không Thức Thời - Đập Nát Tất Cả - Honkai Impact 3',210000,'54.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Hộp quà sinh nhật Elysia 2022 - Honkai Impact 3',360000,'55.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Lịch để bàn chủ đề Đêm Giao Thừa năm 2024 - Honkai Impact 3',240000,'56.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Elysia - Honkai Impact 3 - Hakimi Studio',4400000,'57.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bộ Keycap Lunar Vow: Crimson Love - Honkai Impact 3 - Dake Studio',670000,'58.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Bộ Keycap Seele Vollerei Herrscher of Rebirth - Honkai Impact 3 - Dake Studio',670000,'59.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Standee chủ đề Snowy Delight - Honkai Impact 3',205000,'60.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,1,0,NULL,NULL),
    ('Robin - Honkai Star Rail - Bingo Studio',20000000,'61.webp',123,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Móc khóa 2 mặt dòng Star Rail LAND - Honkai Star Rail',290000,'62.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Giấy màu acrylic dòng Star Rail LAND - Honkai Star Rail',210000,'63.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Móc khóa acrylic dòng Star Rail LAND - Honkai Star Rail',130000,'64.jpg',11,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Huy hiệu dòng Star Rail LAND - Honkai Star Rail',70000,'64.webp',112,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Băng đô nhồi bông Pom pom - Honkai Star Rail',190000,'65.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Gối chủ đề Quỳnh Ngọc Đế Viên của Qingque - Honkai Star Rail',800000,'66.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Gối chữ U chủ đề Blue Bird của Qingque - Honkai Star Rail',380000,'67.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Kafka - Honkai Star Rail - IU Studio',5800000,'68.webp',888,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Sam: Boss - Honkai Star Rail - Shu Ju Hong Liu Studio',5000000,'69.webp',121,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Black Swan - Honkai Star Rail - Moonlight Studio',5400000,'70.webp',3111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Áo nỉ Dan Heng - Honkai Star Rail',1000000,'71.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Áo khoác dài Dan Heng - Honkai Star Rail',1980000,'72.webp',1212,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Quần dài Dan Heng - Honkai Star Rail',1200000,'73.webp',456,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Túi đeo chéo Dan Heng - Honkai Star Rail',1080000,'74.webp',131,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Huy hiệu kim loại dòng Búp bê chibi - Honkai Star Rail',200000,'75.webp',1345,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Hộp đựng thẻ PU loại dòng Búp bê chibi - Honkai Star Rail',240000,'76.jpg',1234,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Búp bê chibi - Honkai Star Rail',405000,'76.webp',765,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Vòng đeo cổ Rakshasa của Luocha - Honkai Star Rail',520000,'77.webp',121,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Chuỗi trang sức Dan Heng - Honkai Star Rail',370000,'78.webp',432,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Huy hiệu nhân vật chủ đề Ngụ Ngôn Ngân Hà - Honkai Star Rail',70000,'79.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Vé laser chủ đề Ngụ Ngôn Ngân Hà - Honkai Star Rail',45000,'80.webp',1200,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Nam châm tủ lạnh chuỗi triển lãm Pom pom - Honkai Star Rail',140000,'81.webp',135,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Blade - Honkai Star Rail - Lingze Studio',7300000,'82.webp',713,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Acheron - Honkai Star Rail - Iron Bird Studio',5000000,'83.webp',987,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Acheron - Honkai Star Rail - FFS Studio',4200000,'84.webp',222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Nendoroid #2456 March 7th - Honkai Star Rail - Good Smile Company',1300000,'85.webp',919,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES
    ('Acheron - Honkai Star Rail - Dark King Studio',5000000,'86.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Acheron - Honkai Star Rail - Fenghua Studio',4200000,'87.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Himeko - Honkai Star Rail - Honey Peach Studio',11800000,'88.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Luka NSFW - Honkai Star Rail - TOC Studio',7000000,'89.webp',888,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Firefly - Honkai Star Rail - HunYu Studio x LoveHolic',4500000,'90.webp',134,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Acheron - Honkai Star Rail - Hakimi Studio',5800000,'91.webp',865,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Acheron - Honkai Star Rail - Fallen Angel Studio',14500000,'92.webp',157,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Acheron - Honkai Star Rail - ABsinthe Studio 1',6000000,'93.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Acheron - Honkai Star Rail - ABsinthe Studio 2',7000000,'94.jpeg',167,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Bộ phụ kiên dành riêng cho Mô hình Silver Wolf - Honkai Star Rail - Hakimi Studio',1300000,'95.webp',135,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Firefly - Honkai Star Rail - Arctic Wolf Studio',6000000,'96.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Búp bê bông Kafka - Honkai Star Rail - Ajong',800000,'97.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Búp bê bông Fu Xuan - Honkai Star Rail - Ajong',670000,'98.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Búp bê bông Firefly - Honkai Star Rail - Ajong',670000,'99.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Búp bê bông Sparkle - Honkai Star Rail - Ajong',670000,'100.webp',765,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Búp bê bông Acheron - Honkai Star Rail - Ajong',670000,'101.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Búp bê cầu nắng - Honkai Star Rail - Micola',240000,'102.webp',876,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Standee Sparkle - Honkai Star Rail - Cat House',235000,'103.webp',987,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Standee Dr. Ratio - Honkai Star Rail - Cat House',235000,'104.jpeg',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Standee Huohuo - Honkai Star Rail - Cat House',235000,'105.jpeg',222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Silver Wolf - Honkai Star Rail - Mi Xun Studio',5700000,'104.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Huohuo - Honkai Star Rail - FWS Studio',6500000,'105.webp',147,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Bộ bưu thiệp giấy chuỗi sự kiện \"Chúc mừng năm mới\" - Honkai Star Rail',160000,'106.webp',865,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Móc khóa Acrylic chuỗi sự kiện \"Chúc mừng năm mới\" - Honkai Star Rail',125000,'107.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Huy hiệu tròn chuỗi sự kiện \"Chúc mừng năm mới\" - Honkai Star Rail',70000,'108.webp',167,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Standee cát chảy chủ đề \"Ngụ Ngôn Ngân Hà\" - Honkai Star Rail',285000,'109.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Bộ thẻ sưu tập chủ đề \"Ngụ Ngôn Ngân Hà\" - Honkai Star Rail',60000,'110.webp',222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Huy hiệu Argenti chủ đề \"Đội Kỵ Sĩ Đẹp Thuần Khiết\" - Honkai Star Rail',70000,'111.webp',112,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Bộ thẻ phim Argenti chủ đề \"Đội Kỵ Sĩ Đẹp Thuần Khiết\" - Honkai Star Rail',205000,'112.webp',112,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm','',2,0,NULL,NULL),
    ('Hook - Honkai Star Rail - MK Studio',4200000,'113.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Mũ Beret Nữ March 7th - Honkai Star Rail',440000,'114.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Vòng đeo cổ và Trâm cài March 7th - Honkai Star Rail',590000,'77.jpg',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Cà vạt và Nơ March 7th - Honkai Star Rail',280000,'115.webp',222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Túi đeo chéo March 7th - Honkai Star Rail',1200000,'116.webp',222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Áo sơ mi Nữ March 7th - Honkai Star Rail',800000,'117.webp',888,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Áo khoác March 7th - Honkai Star Rail',1600000,'118.webp',444,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Quần dài March 7th  - Honkai Star Rail',1080000,'119.webp',555,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Áo sơ mi March 7th  - Honkai Star Rail',920000,'120.webp',679,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Túi đeo vai March 7th - Honkai Star Rail',1000000,'121.webp',842,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Chân váy Nữ March 7th - Honkai Star Rail',1200000,'122.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Mô hình chibi đoàn tàu Honkai Star Rail Vol.1',90000,'123.webp',234,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Tingyun - Honkai Star Rail - miHoYo x Myethos',850000,'124.webp',761,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Sparkle - Honkai Star Rail - Miyin Studio x Arctic Wolf Studio',5200000,'125.webp',874,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Hanabi - Honkai Star Rail - Ocelot Studio',5200000,'126.webp',312,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES
    ('Silver Wolf - Honkai Star Rail - YaoMengMeng Studio',4000000,'105.jpeg',813,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Mô hình lắp ráp Đội tàu Astral - Honkai Star Rail - SetBricks',690000,'78.jpg',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Ellen Joe - Zenless Zone Zero - Roll Studio',7000000,'127.webp',222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Hoshimi Miyabi - Zenless Zeno Zero - KiKi Studio',6300000,'128.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Nicole Demara - Zenless Zone Zero - ABsinthe Studio',6400000,'129.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Nicole Demara - Zenless Zone Zero - ABsinthe Studio 2',7000000,'124.webp',234,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Standee cát chảy chủ đề \"Ngụ Ngôn Ngân Hà\" - Honkai Star Rail',70000,'108.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Móc khóa Acrylic chuỗi sự kiện \"Chúc mừng năm mới\" - Honkai Star Rail',4000000,'123.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Vé Laser chủ đề Flower Festival - Honkai Impact 3',50000,'4.webp',1121,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Elysia - Honkai Impact 3 - Fenghua Studio',6600000,'5.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Elysia: Wedding ver - Honkai Impact 3 - Yuannai Studio',5000000,'6.jpeg',545,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Lunar Vow - Honkai Impact 3 - Mantou',620000,'7.jpeg',887,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Túi đeo chéo Dan Heng - Honkai Star Rail',1080000,'74.webp',131,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Huy hiệu kim loại dòng Búp bê chibi - Honkai Star Rail',200000,'75.webp',1345,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Hộp đựng thẻ PU loại dòng Búp bê chibi - Honkai Star Rail',240000,'76.jpg',1234,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê chibi - Honkai Star Rail',405000,'76.webp',765,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Kafka - Honkai Star Rail - Ajong',800000,'97.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Fu Xuan - Honkai Star Rail - Ajong',670000,'98.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Firefly - Honkai Star Rail - Ajong',670000,'99.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Sparkle - Honkai Star Rail - Ajong',670000,'100.webp',765,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,2,0,NULL,NULL),
    ('Búp bê bông Acheron - Honkai Star Rail - Ajong',670000,'101.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê cầu nắng - Honkai Star Rail - Micola',240000,'102.webp',876,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Standee Sparkle - Honkai Star Rail - Cat House',235000,'103.webp',987,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES
    ('Standee Dr. Ratio - Honkai Star Rail - Cat House',235000,'104.jpeg',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Khối Acrylic cát chảy chủ đề Flower Festival - Honkai Impact 3',205000,'1.webp',1220,'Mô tả chi tiết: Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,'2024-05-13 06:25:26',NULL),
    ('Túi đeo Lunar Vow chủ đề \"Lời Hứa Dưới Ánh Trăng\" - Honkai Impact 3',1030000,'12.webp',2000,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Elysia Herrscher of Human: Hương Đào Mùa Xuân - Honkai Impact 3 - Ajong',670000,'8.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Blindbox Huy hiệu tròn dòng CG Honkai Impact 3',70000,'13.webp',1912,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Lunar Vow - Honkai Impact 3 - Mantou',620000,'7.jpeg',887,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Túi đeo Lunar Vow chủ đề \"Lời Hứa Dưới Ánh Trăng\" - Honkai Impact 3',1030000,'12.webp',2000,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Elysia - Honkai Impact 3 - Fenghua Studio',6600000,'5.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Lunar Vow - Honkai Impact 3 - Mantou',620000,'7.jpeg',887,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Elf Elysia - Honkai Impact 3 - Ajong',670000,'9.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Giá đỡ kính Acrylic chủ đề Nhân vật Raiden Mei - Honkai Impact 3',210000,'11.webp',1918,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê Bronya Zaychik: SilverWing \"Thái Độ Phi Phàm\" - Honkai Impact 3 - Mantou',620000,'22.webp',181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Standee nhân vật 2.0 - Honkai Impact 3',205000,'28.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê Elysia Herrscher of Human:Ego - Honkai Impact 3 - Mantou',620000,'34.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Card raster CG - Honkai Impact 3',60000,'36.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Hộp quà sinh nhật Fu Hua Garuda 2024 - Honkai Impact 3',360000,'44.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Vé Laser chủ đề Flower Festival - Honkai Impact 3',50000,'4.webp',1121,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Elysia: Wedding ver - Honkai Impact 3 - Yuannai Studio',5000000,'6.jpeg',545,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê bông Elysia Herrscher of Human: Hương Đào Mùa Xuân - Honkai Impact 3 - Ajong',670000,'8.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Bộ huy hiệu Vết Thánh ver 2.0 - Honkai Impact 3',110000,'19.webp',1911,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Huy hiệu tròn 13 Anh Kiệt Trục Hỏa - Honkai Impact 3',75000,'20.webp',181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê Seele Vollerei: Herrscher of Rebirth - Honkai Impact 3 - Mantou',620000,'21.webp',192,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Búp bê Bronya Zaychik: SilverWing \"Thái Độ Phi Phàm\" - Honkai Impact 3 - Mantou',620000,'22.webp',181,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Móc khóa chủ đề \"Lucky Life\" - Honkai Impact 3',165000,'24.webp',999,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,3,0,NULL,NULL),
    ('Arlecchino - Genshin Impact - Atlas Studio',5400000,'130.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Bộ Tranh Acrylic và Huy hiệu chủ đề Quan Chấp Hành Fatui - Genshin Impact',70000,'131.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Bộ tách trà và đĩa của Arlecchino - Genshin Impact',650000,'132.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Bộ CD và thẻ NFC \"Ember Fire\" của Arlecchino - Genshin Impact x QQ Music',300000,'133.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Standee nhân vật vùng đất Focalors - Genshin Impact',205000,'134.webp',2222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Huy hiệu tròn nhân vật vùng đất Focalors - Genshin Impact',60000,'135.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Khung tranh Acrylic chủ đề Genshin Impact',245000,'136.webp',2222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Móc khóa Jiachen dòng Happy Birthday - Genshin Impact',125000,'137.webp',2222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Nam châm tủ lạnh Jiachen dòng Happy Birthday - Genshin Impact',110000,'138.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Giấy màu mini Jiachen dòng Happy Birthday - Genshin Impact',110000,'139.webp',222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Huy hiệu và Móc khóa Chiori: Tay Áo Trình Diễn - Genshin Impact',70000,'140.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Standee giá đỡ điện thoại sự kiện \"Thất Thánh Triệu Hồi\" - Genshin Impact',245000,'141.webp',2222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Móc bông búp bê dòng Pháp Sư Vực Sâu - Genshin Impact',111199,'142.webp',222,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Ly thủy tinh dòng Yae Miko - Genshin Impact',300000,'143.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Khối tranh cát nhân vật dòng Genshin Impact',175000,'144.webp',332,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Arlecchino - Genshin Impact - Atlas Studio',5400000,'145.webp',1111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('2B - Nier Automata - Imagination Studio x Red Peach A',7600000,'146.webp',111,'Vui lòng liên hệ shop để xác nhận tình trạng sản phẩm',NULL,4,0,NULL,NULL),
    ('Seraphim Boa Hancock - One Piece - Jiuwaihu Studio',2300000,'147.webp',111,NULL,NULL,4,0,NULL,NULL);

INSERT INTO `products` (`product_name`, `product_price`, `product_images`, `product_quantity`, `product_description`, `discount`, `category_id`,`is_deleted`, `created_date`, `url_image`)
VALUES
    ('Asuka - Evangelion - IU Studio',2000000,'148.webp',111,NULL,NULL,4,0,NULL,NULL),
    ('Luffy Nika há miệng - One Piece - Comic Hero Studio',2000000,'149.webp',1111,NULL,NULL,4,0,NULL,NULL),
    ('Genshin Impact Ice Cream Series - ILLegal Factory Studio',1650000,'150.webp',1111,NULL,NULL,4,0,NULL,NULL),
    ('Ellen Joe - Zenless Zone Zero - Roll Studio',7000000,'151.webp',111,NULL,NULL,4,0,NULL,NULL),
    ('Liễu Thần - Thế Giới Hoàn Mỹ - PiJi Studio',20500000,'79.jpg',1111,NULL,NULL,4,0,NULL,NULL),
    ('Vegeta - Dragon Ball - Flipped Studio',13300000,'152.webp',1111,NULL,NULL,4,0,NULL,NULL),
    ('Vegeta - Dragon Ball - Flipped Studio 2',50000000,'153.webp',1111,NULL,NULL,4,0,NULL,NULL),
    ('Hutao chibi - Genshin Impact - Lovely The Beast Studio',47800000,'154.webp',1111,NULL,NULL,4,0,NULL,NULL),
    ('Itadori Yuji - Jujutsu Kaisen - Gugu Studio x Mimo Studio',3400000,'155.webp',1111,NULL,NULL,4,0,NULL,NULL),
    ('Meowth - Pokemon - Mo Wan She Studio',4780000,'156.webp',1111,NULL,NULL,4,0,NULL,NULL),
    ('Lylian - Ghost Blade - TriEagles Studio',22500000,'157.webp',111,NULL,NULL,4,0,NULL,NULL),
    ('Robin - Honkai Star Rail - Bingo Studio',20000000,'158.webp',1111,NULL,NULL,4,0,NULL,NULL),
    ('Nendoroid #2468 Kitasan Black - Uma Musume Pretty Derby - Good Smile Company',1320000,'159.webp',1111,NULL,NULL,4,0,NULL,NULL),
    ('Nendoroid #2461 Hoshino Takanashi - Blue Archive - Good Smile Company',1000110,'160.webp',1111,NULL,NULL,4,0,NULL,NULL),
    ('Mikasa Ackerman - Attack on Titan - Chikara Studio',4100000,'161.webp',111,NULL,NULL,4,0,NULL,NULL),
    ('Blindbox mô hình dòng King\'s Bucket - Honkai Star Rail',95000,'162.webp',999,NULL,NULL,4,0,NULL,NULL),
       ('Jeanne D\' Arc - Fate Grand Order - DT & Ume Studio',20000000,'163.webp',888,NULL,NULL,4,0,NULL,NULL),
    ('Nendoroid #2469 Satono Diamond - Uma Musume Pretty Derby - Good Smile Company',1320000,'164.webp',888,NULL,NULL,4,0,NULL,NULL),
    ('Nendoroid #2476 Ichihime - MahjongSoul - Good Smile Company',1650000,'165.webp',777,NULL,NULL,4,0,NULL,NULL),
    ('Nendoroid #2427 Neo: Traveler - Dungeon Fighter Online - Good Smile Company',1200000,'166.webp',999,NULL,NULL,4,0,NULL,NULL),
    ('Nendoroid #2482 Xerxes Break - PandoraHearts - Good Smile Company',1200000,'80.jpg',777,NULL,NULL,4,0,NULL,NULL),
    ('Nendoroid #2481 Oz Vessalius - PandoraHearts - Good Smile Company',1200000,'167.webp',777,NULL,NULL,4,0,NULL,NULL);
