## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/animefigurestore?characterEncoding=UTF-8
    username: root
    password: Abc12345@
# config db online railway
#    url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/${MYSQL_DB_NAME}?characterEncoding=UTF-8
#    username: ${MYSQL_DB_USERNAME}
#    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
    # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: none
    ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  ## MULTIPART (MultipartProperties)
  servlet:
    multipart:
      # Max file size.
      max-file-size: 10MB
      # Max Request Size
      max-request-size: 10MB
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
jwt:
  privateKey: s30AjBawg1JBD92Gab5t8UDzl/+WSSug1VmLErKG8JA=
#fileUpload:
#  rootPath: ..\animestore\uploads


