## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/animefigurestore?characterEncoding=UTF-8&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    username: root
    password: Abc12345@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
    # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: none
    ## Hibernate Properties
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  ## MULTIPART (MultipartProperties)
  servlet:
    multipart:
      # Max file size.
      max-file-size: 10MB
      # Max Request Size
      max-request-size: 10MB
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB

  security:
    oauth2:
      client:
        registration:
          # Google
          google:
            client-id: ${GG_CLIENT_ID}
            client-secret: ${GG_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid
          # Github
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
          # Facebook
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
  mail:
    host: smtp.gmail.com
    username: ${YOUR_EMAIL}
    ## step1: go to https://myaccount.google.com/security
    ## step2: turn on "2-Step Verification"
    ## step3: go to "App passwords"
    ## step4: register app and copy password gg generate show in screen below code
    ## if not found "APP PASSWORD", you go to link https://myaccount.google.com/apppasswords
    password: ${APP_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  privateKey: s30AjBawg1JBD92Gab5t8UDzl/+WSSug1VmLErKG8JA=

mvc:
  static-path: /images


logging:
  level:
    org.springframework.security: DEBUG

server:
  tomcat:
    relaxed-path-chars: <,>,[,\,],^,`,{,|,},
    relaxed-query-chars: <,>,[,\,],^,`,{,|,},

frontend:
  url: http://localhost:3000/admin/users