#spring.application.name=animestore
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/animefigurestore?characterEncoding=UTF-8
#    username: root
#    password: Abc12345@
    url: jdbc:mysql://viaduct.proxy.rlwy.net:39540/railway?characterEncoding=UTF-8
    username: root
    password: VzVvzNjKMRaWasQNFfdDweYYLDrqRJNS
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 2KB
jwt:
  privateKey: s30AjBawg1JBD92Gab5t8UDzl/+WSSug1VmLErKG8JA=
#fileUpload:
#  rootPath: ..\animestore\uploads


